version: '2.1'

volumes:
  jupyter-settings:
    driver: local

networks:
  traefik_proxy:
    external: true

services:
  jupyter-lab:
      # image: ppsmart/jupyterlab-torch-fastai:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /home/${USER}/Desktop/jupyter-lab-server/projects:/projects
      - /home/${USER}/.kaggle/:/root/.kaggle/
      - /home/${USER}/.ssh:/root/.ssh
      - /home/${USER}/.gitconfig:/root/.gitconfig
      - jupyter-settings:/root/.jupyter/
    networks:
      - "traefik_proxy"
    labels:
       - "traefik.enable=true"
       - "traefik.backend=jupyter-lab"
       - "traefik.docker.network=traefik_proxy"
       - "traefik.frontend.rule=Host:jupyter.localhost"
       - "traefik.odoo.port=8889"
